services:

  backend:
    build:
      context: ./tracker
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=example
    networks:
      - spring-postgres
    depends_on:
      - db
    volumes:
      - ticket_file:/ticket_files

  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432

  frontend:
    build:
      context: ./tracker_frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - /project/node_modules
    networks:
      - react-spring
    depends_on:
      - backend

volumes:
  db-data:
  ticket_file:

secrets:
  db-password:
    file: db/password.txt

networks:
  react-spring:
  spring-postgres: